Updated smtpd_archive to accept an optional destination parameter and to exit if destination doesn't exist

diff --git a/sbin/smtpd_archive b/sbin/smtpd_archive
--- a/sbin/smtpd_archive
+++ b/sbin/smtpd_archive
@@ -4,13 +4,15 @@
 
 service="smtpd"
 set -A src "/etc/mail" "/var/spool/smtpd"
-dst="/var/backups/${service}"
+dst="${1:-/var/backups/${service}}"
 
 host="$(hostname)"
 tool="$(basename "$0")"
 date="$(date +%Y%m%d-%H%M%S)"
 
 if [ ! -d "$dst" ]; then
-  mkdir -p "$dst"
+  echo "ERROR: Destination '${dst}' doesn't exist!"
+  echo "Exiting."
+  exit 1
 fi
 tar czvf "${dst}/${host}-${service}-${date}.tar.gz" "$0" "${src[@]}"
